version: 2
     ethernets:
       eth0:
         dhcp4: false
         dhcp6: false
         addresses:
           - ${ip_address}
         gateway4: 172.20.3.1
         nameservers:
           addresses:
             - 8.8.8.8
